{{- include "srox.init" . -}}

{{- if and (not ._rox.central.db.external) ._rox.system.enablePodSecurityPolicies }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "srox.globalResourceName" (list . "stackrox-central-db-psp") }}
  labels:
    {{- include "srox.labels" (list . "clusterrole" "stackrox-central-db-psp") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "clusterrole" "stackrox-central-db-psp") | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "srox.globalResourceName" (list . "stackrox-central-db") }}
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stackrox-central-db-psp
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "srox.labels" (list . "rolebinding" "stackrox-central-db-psp") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "stackrox-central-db-psp") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "srox.globalResourceName" (list . "stackrox-central-db-psp") }}
subjects:
  - kind: ServiceAccount
    name: central-db
    namespace: {{.Release.Namespace}}

