{{- include "srox.init" . -}}

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "srox.globalResourceName" (list . "stackrox-central-psp") }}
  labels:
    {{- include "srox.labels" (list . "clusterrole" "stackrox-central-psp") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "clusterrole" "stackrox-central-psp") | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "srox.globalResourceName" (list . "stackrox-central") }}
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stackrox-central-psp
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "srox.labels" (list . "rolebinding" "stackrox-central-psp") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "stackrox-central-psp") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "srox.globalResourceName" (list . "stackrox-central-psp") }}
subjects:
  - kind: ServiceAccount
    name: central
    namespace: {{.Release.Namespace}}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "srox.globalResourceName" (list . "stackrox-central") }}
  labels:
    {{- include "srox.labels" (list . "podsecuritypolicy" "stackrox-central") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "podsecuritypolicy" "stackrox-central") | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
    - 'hostPath'
  {{ if ._rox.central.persistence.hostPath -}}
  allowedHostPaths:
    - pathPrefix: {{ ._rox.central.persistence.hostPath }}
  {{- end}}
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAs'
    ranges:
      - min: 4000
        max: 4000
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 4000
        max: 4000

{{- if and ._rox.env.openshift ._rox.system.createSCCs }}
---

kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: {{ include "srox.globalResourceName" (list . "stackrox-central") }}
  labels:
    {{- include "srox.labels" (list . "securitycontextconstraints" "stackrox-central") | nindent 4 }}
  annotations:
    kubernetes.io/description: stackrox-central is the security constraint for the central server
    {{- include "srox.annotations" (list . "securitycontextconstraints" "stackrox-central") | nindent 4 }}
allowHostDirVolumePlugin: {{ ._rox.central.persistence.hostPath | not | not }}
allowedCapabilities: []
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
  ranges:
    - max: 4000
      min: 4000
priority: 0
readOnlyRootFilesystem: true
requiredDropCapabilities: []
runAsUser:
  type: MustRunAs
  uid: 4000
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - '*'
users:
  - system:serviceaccount:{{ .Release.Namespace }}:central
volumes:
  - '*'

{{- else if eq ._rox.env.openshift 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-central-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "role" "use-central-scc") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "role" "use-central-scc") | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - anyuid
  {{- if ._rox.central.persistence.hostPath }}
  - hostmount-anyuid
  {{- end }}
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: central-use-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "rolebinding" "central-use-scc") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "central-use-scc") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-central-scc
subjects:
- kind: ServiceAccount
  name: central
  namespace: {{.Release.Namespace}}
{{- end }}
